stages:
  - build
  - test

variables:
  # Переменные окружения для баз данных
  USER_SERVICE_PG_USER: testuser
  USER_SERVICE_PG_PASS: testpassword
  USER_SERVICE_PG_DB: userdb
  USER_SERVICE_PG_HOST: user_service_database
  PROJECT_SERVICE_PG_USER: testuser
  PROJECT_SERVICE_PG_PASS: testpassword
  PROJECT_SERVICE_PG_DB: projectdb
  PROJECT_SERVICE_PG_HOST: project_service_database
  # Переменные для Kafka
  KAFKA_BROKER: kafka:9092
  ZOOKEEPER_HOST: zookeeper:2181

build:
  stage: build
  script:
    - echo "Building services..."
    - go build -o bin/user_service ./UserService
    - go build -o bin/project_service ./project-service
    - go build -o bin/notification_service ./notification-service
  artifacts:
    paths:
      - bin/

test_user_service:
  stage: test
  services:
    - name: postgres:16.2-alpine3.19
      alias: user_service_database
  variables:
    POSTGRES_USER: $USER_SERVICE_PG_USER
    POSTGRES_PASSWORD: $USER_SERVICE_PG_PASS
    POSTGRES_DB: $USER_SERVICE_PG_DB
  script:
    - echo "Waiting for services..."
    - until pg_isready -h $USER_SERVICE_PG_HOST -p 5432 -U $USER_SERVICE_PG_USER; do sleep 1; done
    - echo "Running tests for User Service..."
    - go test ./user_service/... -v -cover -coverprofile=user_service.coverage
  artifacts:
    paths:
      - user_service.coverage

test_project_service:
  stage: test
  services:
    - name: postgres:16.2-alpine3.19
      alias: project_service_database
    - name: confluentinc/cp-zookeeper:7.5.0
      alias: zookeeper
    - name: confluentinc/cp-kafka:7.5.0
      alias: kafka
  variables:
    POSTGRES_USER: $PROJECT_SERVICE_PG_USER
    POSTGRES_PASSWORD: $PROJECT_SERVICE_PG_PASS
    POSTGRES_DB: $PROJECT_SERVICE_PG_DB
  script:
    - echo "Waiting for services..."
    - until pg_isready -h $PROJECT_SERVICE_PG_HOST -p 5432 -U $PROJECT_SERVICE_PG_USER; do sleep 1; done
    - echo "Running tests for Project Service..."
    - go test ./project_service/... -v -cover -coverprofile=project_service.coverage
  artifacts:
    paths:
      - project_service.coverage

test_notification_service:
  stage: test
    - name: confluentinc/cp-zookeeper:7.5.0
      alias: zookeeper
    - name: confluentinc/cp-kafka:7.5.0
      alias: kafka
  script:
    - echo "Running tests for Project Service..."
    - go test ./notification_service/... -v -cover -coverprofile=notification_service.coverage
  artifacts:
    paths:
      - notification_service.coverage